version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsinsight-admin-ui
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    # depends_on: # Removed strict dependency since we might connect to external DB
    #   - db
    networks:
      - newsinsight-net

  db:
    image: postgres:15-alpine
    container_name: newsinsight-admin-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - newsinsight-net

volumes:
  postgres_data:


networks:
  newsinsight-net:
    driver: bridge
