version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsinsight-admin-ui
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    # depends_on: # Removed strict dependency since we might connect to external DB
    #   - db
    networks:
      - newsinsight-net
networks:
  newsinsight-net:
    driver: bridge
